### ISSUE TITLE
全員参加できる start with all を実装したい

### ISSUE THREAD

**Issue by millay1114** [setokinto/slack-shogi#26]
チャンネル参加者全員で出来るモードを実装したい

**Comment by kouki-dan** [comment]
How do we play in this mode?

If user validation which other player cannot play in this version removed, the mode is completed?

**Comment by millay1114** [comment]
* support to ``start with all``
* remove to the user validation

**Comment by kouki-dan** [comment]
Who does implement this?

**Comment by kouki-dan** [comment]
If a slack-team has a user whose name is "all" exists, how do you do it?
