### ISSUE TITLE
outputモジュールを作る

### ISSUE THREAD

**Issue by kouki-dan** [setokinto/slack-shogi#3]
slackへのoutputのモジュールを作る

- 将棋盤モジュール担当者からoutputの形式を聞き出す
- slackに表示するとそのままいい感じに出力できる感じのテキストに盤面の状態を変換する
- それを返す何かを作る

**Comment by KazukiYoshii** [comment]
はいやります。

**Comment by KazukiYoshii** [comment]
[WIP] outputモジュールを作る #8

**Comment by kouki-dan** [comment]
絵文字が登録されてなかったら自動で必要な絵文字を全部登録してくれるbotとかあるといいね。
API的にできるのかわからんけど。

**Comment by kouki-dan** [comment]
↑は #11 で作った
