### ISSUE TITLE
最後に指した手が分かるようにしたい

### ISSUE THREAD

**Issue by millay1114** [setokinto/slack-shogi#36]
案１：赤い背景の駒を用意して、最後に指した手は背景が赤くなるようにする（atyatyaが大変）
案２：単にテキストで出力する。

**Comment by kouki-dan** [comment]
解決した？

**Comment by millay1114** [comment]
解決してない

**Comment by millay1114** [comment]
絵文字案で行ってみる。絵文字はatyatyaがあちゃちゃっと作ってくれる（らしい）

絵文字スクリプトのここに追加と
https://github.com/setokinto/slack-shogi/blob/master/input_emojis/input_emojis.py#L9

make_board_emojiのここに x=last_x & y=last_y なら _last とかついた絵文字に変換する感じでダメかな？
https://github.com/setokinto/slack-shogi/blob/master/app/modules/shogi_output.py#L66
